[package]
name = "jeffohh/simplenav"
description = "A simple pathfinding wrapper with steering behaviors."
license = "MIT"
authors = ["PhantomVisual"]
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["rokit.toml"]

[dependencies]
janitor = "howmanysmall/janitor@1.18.3"
lemonsignal = "data-oriented-house/lemonsignal@1.11.0"